### ISSUE TITLE
Getting error while generating output for secondary priority files

### ISSUE THREAD

**Issue by murli1201** [NSSAC/CINES#85] opened 2020-05-29 11:38 UTC
@cckuhlman  @Lucaslhm 

Hi Chris, Lucas,

We have generated the driver codes for most of the secondary priority methods (except the ones that produced datatype errors). We tried generating outputs for most of them but see an error - "Error in invoking the library method." for all these methods.

I observed that all such methods contain parameters that accept string as an input type (we haven’t come across such methods earlier):
FNmPref: string (input)
DescStr: string (input)

I tried giving appropriate string input, following the examples in the documentation but it did not help.

Could you please help me in finding the solution. I am attaching the driver codes & the folder consisting of input graphs and run files so you may test.

[secondary priority.zip](https://github.com/NSSAC/CINES/files/4701521/secondary.priority.zip)

Thanks,
Murli.

**Comment by cckuhlman** [comment] 2020-06-01 10:45
@murli1201 

Hey Murli:

Talking about method PlotClustCf.  See https://snap.stanford.edu/snappy/doc/reference/PlotClustCf.html?highlight=plotclustcf

I cannot tell for sure what is going on.  But I think it is this.  Check the snap input file for this.  Each occurrence of "string" or "String" needs to be changed to "str".  That is, the primitive type string is represented as "str" (not "string" or "String").  Looking at the driver code, this is suggested as the cause.  Each of these parameters is an str, and should not require 'inputFile" type variables.

Similarly, integers are "int" and Boolean is "bool".  See the constants file for the parsing code.

In future, for an issue, please include the (1) method name, (2) the number assigned to the method, (3) the snap input file, (4) the IRs, (5) the driver code, (6) all files for the verification testing.

I could not locate the snap method text input file in the github repo that you were using, so am not positive about the "str" issue, but it looks like that.

It also appears that this is the issue for PlotEigValDistr and for PlotEigValRank.

chris

**Comment by anju-thute** [comment] 2020-06-01 11:28
@cckuhlman @Lucaslhm 

Hey Chris,

Thanks for your update!
Murali and I have changed the primitive type "string" to "str" in the input file. Then we parse the input file and generated the driver code for the snap method **PlotClustCf**. We have executed the driver code and it got completed.

Thanks,
Anju

**Closed** 2020-06-01 11:47 UTC
