### ISSUE TITLE
Initial States -> Number of Nodes

### ISSUE THREAD

**Issue by dmachi** [NSSAC/CINES#171] opened 2021-05-18 16:09 UTC
If you click on the number of nodes field under Initial States and then click away, this crashes the application because there is no value set.  This also happens if you tab away from that field with no value set.

**Comment by murli1201** [comment] 2021-05-18 17:32
Hello Dustin,

I have fixed the number of nodes issue and committed it to the CSonNet branch. I have also merged it to the master branch.
Can you please test it again and check if the issue is solved?

Thank you,
Murli.

**Closed** 2021-06-10 09:27 UTC
