### ISSUE TITLE
When uploading a file, the status is seen as pending for sometime and then ultimately the file is uploaded - but its size is 0 KB

### ISSUE THREAD

**Issue by murli1201** [NSSAC/CINES#152] opened 2021-04-20 14:34 UTC
Steps - 	
1) In file manger - select file in file upload dialog, set its type
2) and click on Upload
3) In the console - the status is seen as pending for sometime and then ultimately the file is uploaded - but its size is 0 KB

![file status- pending](https://user-images.githubusercontent.com/54397265/115413887-30b24580-a213-11eb-8ffc-5df2ce3082ea.png)

**Comment by dmachi** [comment] 2021-04-20 21:53
I am not able to reproduce this currently.  I think what was happening here was something else.  It appears that the put portion of the upload was failing, but the post portion was succeeding.   I suspect that this was a two part problem 1) the environment was not instantiated properly before launch of the file store, so it was using the wrong version of singularity and 2) there was an error in serializing errors/exceptions.   My recent bugfix for error handling fixes the latter case, and I also resolved the environment/module load issue. Please test again.

**Comment by murli1201** [comment] 2021-04-21 11:55
We are still facing the same issue for uploading a file. Please refer the video attached to reproduce.  


https://user-images.githubusercontent.com/54397265/115549646-83006e80-a2c6-11eb-848d-d6ebea6c466f.mp4

**Comment by dmachi** [comment] 2021-04-21 15:48
This has nothing to do with uploading.  I'm closing this ticket in favor of a common one tracking the problem seen here: #153

**Closed by dmachi** 2021-04-21 15:48 UTC
